name: 'Get Modified/Added Files'
description: Custom Action to get a JSON object of added/modified files between commits.
author: GeneralMills
inputs:
  token:
    description: 'GitHub Token for API Requests'
    required: true
    default: ${{ github.token }}
outputs:
  files: JSON string of files
runs:
  using: 'node12'
  main: 'dist/index.js'
